import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./hero-bg.css";
import NavBar from "@/components/HomePage/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative">
          <div className="absolute mt-0 top-0 left-0 w-full z-10">
            <NavBar />
          </div>
          <div className="pt-[20]">
            {/* Add top padding to push children below the overlapping NavBar */}
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
