export const diseasesList: string[] = [
  "Alzheimer's disease",
  "Parkinson's disease",
  "Huntington's disease",
  "Amyotrophic lateral sclerosis (ALS)",
  "Multiple sclerosis (MS)",
  "Epilepsy",
  "Stroke",
  "Migraine",
  "Traumatic brain injury",
  "Spinal cord injury",
  "Frontotemporal dementia",
  "Lewy body dementia",
  "Cerebral palsy",
  "Autism spectrum disorder",
  "Schizophrenia",
  "Hypertension",
  "Coronary artery disease",
  "Heart failure",
  "Atrial fibrillation",
  "Myocardial infarction (heart attack)",
  "Peripheral artery disease",
  "Cardiomyopathy",
  "Congenital heart defects",
  "Rheumatic heart disease",
  "Pulmonary hypertension",
  "Anemia",
  "Sickle cell disease",
  "Hemophilia",
  "Thalassemia",
  "Leukemia",
  "Lymphoma",
  "Multiple myeloma",
  "Hemochromatosis",
  "Polycythemia vera",
  "Aplastic anemia",
  "Cystic fibrosis",
  "Phenylketonuria (PKU)",
  "Tay-Sachs disease",
  "Gaucher disease",
  "Fabry disease",
  "Niemann-Pick disease",
  "Wilson's disease",
  "Marfan syndrome",
  "Ehlers-Danlos syndrome",
  "Mitochondrial disorders",
  "COVID-19",
  "Tuberculosis",
  "HIV/AIDS",
  "Hepatitis B",
  "Hepatitis C",
  "Influenza",
  "Malaria",
  "Dengue fever",
  "Zika virus",
  "Ebola virus disease",
  "Chikungunya",
  "Lyme disease",
  "Syphilis",
  "Gonorrhea",
  "Human papillomavirus (HPV)",
  "Rheumatoid arthritis",
  "Lupus (SLE)",
  "Psoriasis",
  "Psoriatic arthritis",
  "Ankylosing spondylitis",
  "Crohn's disease",
  "Ulcerative colitis",
  "Celiac disease",
  "Sjögren's syndrome",
  "Vasculitis",
  "Depression",
  "Bipolar disorder",
  "Anxiety disorders",
  "Obsessive-compulsive disorder (OCD)",
  "Post-traumatic stress disorder (PTSD)",
  "Attention-deficit/hyperactivity disorder (ADHD)",
  "Eating disorders",
  "Substance use disorders",
  "Schizoaffective disorder",
  "Borderline personality disorder",
  "Breast cancer",
  "Lung cancer",
  "Prostate cancer",
  "Colorectal cancer",
  "Pancreatic cancer",
  "Ovarian cancer",
  "Cervical cancer",
  "Liver cancer",
  "Kidney cancer",
  "Melanoma",
  "Bladder cancer",
  "Esophageal cancer",
  "Stomach cancer",
  "Thyroid cancer",
  "Testicular cancer",
  "Type 1 diabetes",
  "Type 2 diabetes",
  "Hyperthyroidism",
  "Hypothyroidism",
  "Polycystic ovary syndrome (PCOS)",
];
